### ISSUE TITLE
Update `azservicebus`

### ISSUE THREAD

**Issue by minghuaw** [minghuaw/azservicebus#3]
- [x] minghuaw/azure-sdk-for-rust#9
- [x] Fix equivalent of minghuaw/azure-sdk-for-rust#7 
- [x] minghuaw/azure-sdk-for-rust#10
